### PR TITLE
Adds ll_intercom_show_widget filter

### PR DESCRIPTION
**Pull request by bradaric**
Would still be great to be able to show/hide just the widget...

### CODE REVIEW

**Comment by lumpysimon** [comment]
Thanks Alex - I'll test this ASAP and if it works I'll be happy to merge it in.

**Comment by bradaric** [comment]
I've adjusted a bit the widget hiding code - it uses CSS now instead of omitting portions of JS. Let me know if it works better for you. Thanks :)

**Comment by lumpysimon** [comment]
Hi Alex

It turns out there is a proper way to do this that doesn't involve CSS or JavaScript, or any changes to the plugin code. There are two steps:
1. Disable the messenger via your intercom.io dashboard ([see this article](http://docs.intercom.io/faqs/can-i-turn-off-the-in-app-messenger-button)).
2. Use the `ll_intercom_activator` filter to return `'#IntercomDefaultWidget'` on pages you wish to show the messenger (this overrides the disable setting), and a blank string on pages you do not wish to show it.

I've added a couple of FAQ items about it to readme.txt. It's based on [this article in the Intercom help docs](http://docs.intercom.io/configuring-Intercom/in-app-messenger#can-i-make-the-in-app-messenger-only-available-to-selected-users).

I've tested and it looks to work well. Can you also test it by installing v1.1.1 from GitHub? If it works for you I'll upload to the wordpress.org plugin repo.

Thanks
Simon

**Comment by bradaric** [comment]
Hi,

Can't test right now, but it sounds promising. Will let you know later today or tomorrow morning.

Take care,
Alex

**Comment by lumpysimon** [comment]
Hi Alex

Did you have a chance to try this out?

Cheers
Simon

**Comment by bradaric** [comment]
Hi Simon,

Sorry, never got to it in the end :|

Take care,
Alex

**Pull request closed without merging**
